apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mongodb
  labels:
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: mongodb-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: mongodb
  dnsNames:
    - {{ template "mongodb.hostname" . }}
    - localhost
    - "127.0.0.1"
