apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: service-registry
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: service-registry-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: service-registry
  dnsNames:
  - service-registry.{{ .Release.Namespace }}.svc.cluster.local
  - localhost
