apiVersion: v1
kind: Service
metadata:
  name: service-registry-lb
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8761
    name: eureka
  selector:
    app: service-registry
