apiVersion: v1
kind: Secret
metadata:
  name: service-registry-secrets
type: Opaque
data:
  trustStorePassword: {{ .Values.trustStorePassword | default uuidv4 | b64enc}}
  keyStorePassword: {{ .Values.keyStorePassword | default uuidv4 | b64enc }}
