apiVersion: v1
kind: Secret
metadata:
  name: service-registry-secrets
  labels:
    chart: {{ template "service-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  trustStorePassword: {{ .Values.trustStorePassword | default uuidv4 | b64enc}}
  keyStorePassword: {{ .Values.keyStorePassword | default uuidv4 | b64enc }}
