apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-registry
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: service-registry
spec:
  ports:
  - name: eureka
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8761
  selector:
    app: service-registry
    release: {{ .Release.Name }}
  type: ClusterIP
