apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-registry
  name: service-registry
  release: {{ .Release.Name }}
spec:
  ports:
  - name: eureka
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8761
  selector:
    app: service-registry
  type: ClusterIP
