apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-registry
    chart: {{ template "service-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: service-registry
spec:
  ports:
  - name: eureka
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8761
  selector:
    app: service-registry
  type: ClusterIP
{{ if .Values.service.expose -}}
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-lb
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8761
    name: eureka
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: service-registry
{{- end }}