apiVersion: v1
kind: Service
metadata:
  name: api-gateway-lb-a
  namespace: kryption
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: tomcat
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-lb-b
  namespace: kryption
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: tomcat
  selector:
    app: api-gateway
