apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: {{ .Values.issuerNamespace }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.ServiceName }}
spec:
  ca:
    secretName: ca-key-pair
