spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    fetch-registry: false
