spring:
  application:
    name: service-registry

server:
  port: 8761
  ssl:
    enabled: true
    key-store: file:/app/server.p12
    key-store-type: pkcs12
    key-store-password: secret
    key-alias: service-registry

eureka:
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    secure-port-enabled: true
    secure-port: 8761
    hostname: https://service-registry.default.svc.cluster.local/eureka
  client:
    fetch-registry: false
    service-url:
      defaultZone: https://service-registry.default.svc.cluster.local/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file: /data/logs/registry.log
