apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume: mongodb-data
  name: mongodb-data
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
