apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: mongodb-data
  name: mongodb-data
  namespace: kryption
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  capacity:
    storage: 10Gi
