apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: mysql-data
  name: mysql-data
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: mysql-logs
  name: mysql-logs
spec:
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
