apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume: rabbit-data
  name: rabbit-data
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
