server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: chat_route
        uri: lb://CHAT-SERVICE
        predicates:
        - Path=/chat/**
        filters:
        - RewritePath=/chat/(?<remaining>.*), /$\{remaining}
      - id: auth_route
        uri: lb://AUTHENTICATION-SERVICE
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<remaining>.*), /$\{remaining}
      - id: realtime_route
        uri: ws://rabbit:15674/ws
        predicates:
        - Path=/realtime/chat/**

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.echoseven.kryption: debug
  file: /data/logs/gateway.log

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 30
  instance:
    appname: api-gateway
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
