server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/app/server.p12
    key-store-type: pkcs12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: api-gateway
    trust-store: file:/app/trusts.jks
    trust-store-password: ${TRUSTSTORE_PASSWORD}
    trust-store-type: jks

spring:
  application:
    name: api-gateway
  cloud:
    httpclientfactories:
      ok:
        enabled: true
    gateway:
      httpclient:
        ssl:
          trustedX509Certificates:
          - /trusts/tls.crt
      routes:
      - id: chat_route
        uri: lb://CHAT-SERVICE
        predicates:
        - Path=/chat/**
        filters:
        - RewritePath=/chat/(?<remaining>.*), /$\{remaining}
      - id: auth_route
        uri: lb://AUTHENTICATION-SERVICE
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<remaining>.*), /$\{remaining}
      - id: realtime_route
        uri: ${WEB_STOMP_URI}
        predicates:
        - Path=/realtime/chat/**

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.echoseven.kryption: debug
  file: /data/logs/gateway.log

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    appname: api-gateway
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
