server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.echoseven.kryption: debug
  file: /data/logs/gateway.log

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 30
  instance:
    appname: api-gateway
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

zuul:
  routes:
    auth:
      path: /auth/**
      service-id: authentication-service
      sensitive-headers:
    chat:
      path: /chat/**
      service-id: chat-service
      sensitive-headers:
    login:
      path: /login
      service-id: authentication-service
  ignored-services:
    - service-registry
    - authentication-service
    - chat-service
