# Default values for chat-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 
  tag: latest
  pullPolicy: IfNotPresent

keyStorePassword:
trustStorePassword:
javaOpts: -Xmx2000m -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=cloud  -Djavax.net.ssl.trustStore=/app/trusts.jks

service:
  type: ClusterIP
  port: 443
  targetPort: 8243

claims:
  mongodb:
    storage: 10Gi
    volumeMode:
    annotations: {}

mongodb:
  existingSecret: mongodb-secrets
  mongodbUsername: kryption
  mongodbDatabase: kryption
  persistence:
    existingClaim: mongodb-pvc
  mongodbExtraFlags: 
    - --sslMode=requireSSL
    - --sslPEMKeyFile=/ssl/keys/mongodb.pem
    - --sslCAFile=/ssl/ca/tls.crt
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

rabbitmq-ha:
  rabbitmqUsername: kryption
  prometheus:
    exporter:
      enabled: false
    operator:
      enabled: false
  rabbitmqCert:
    enabled: true
    existingSecret: rabbitmq-tls
    existing-ca: ca-key-pair
  rabbitmqAmqpsSupport:
    enabled: true
    config: |
      listeners.ssl.default             = 5671
      ssl_options.cacertfile            = /ssl/ca/tls.crt
      ssl_options.certfile              = /ssl/cert/tls.crt
      ssl_options.keyfile               = /ssl/cert/tls.key
      ssl_options.verify                = verify_peer
      ssl_options.fail_if_no_peer_cert  = false
  rabbitmqWebSTOMPPlugin:
    enabled: true
  rabbitmqHttpAuthPlugin:
    enabled: true
    config: |
      auth_backends.1 = rabbit_auth_backend_http
      auth_backends.2 = internal
      auth_http.http_method = post
      auth_http.user_path = https://authentication-service.default.svc.cluster.local/amqp/user
      auth_http.vhost_path = https://authentication-service.default.svc.cluster.local/amqp/vhost
      auth_http.resource_path = https://authentication-service.default.svc.cluster.local/amqp/resource
      auth_http.topic_path = https://authentication-service.default.svc.cluster.local/amqp/topic