apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-registry
  name: service-registry
  namespace: kryption
spec:
  ports:
  - name: eureka
    port: 80
    targetPort: 8761
  selector:
    app: service-registry
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-lb
  namespace: kryption
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8761
      name: eureka
  selector:
    app: service-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: service-registry
  name: service-registry
  namespace: kryption
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - env:
        - name: eureka.client.service-url.default-zone
          value: http://service-registry.kryption.svc.cluster.local/eureka
        name: service-registry
        image: service-registry:latest
        ports:
        - containerPort: 8761
      restartPolicy: Always
  selector:
    matchLabels:
      app: service-registry
