apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume: mongodb-data
  name: mongodb-data
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
