apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume: rabbit-data
  name: rabbit-data
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
