apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert
    kompose.version: 1.13.0 (84fa826)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - env:
        - name: EUREKA_URL
          value: http://service-registry:8761/eureka/
        image: api-gateway
        name: api-gateway
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-gateway
