apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: authentication-service
  name: authentication-service
spec:
  ports:
  - name: "8180"
    port: 8180
    targetPort: 8180
  selector:
    io.kompose.service: authentication-service
status:
  loadBalancer: {}
