apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-registry
  name: service-registry
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    service: service-registry
