{{- if not .Values.ssl.existingCerts }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mysql
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ .Values.ssl.secret }}
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: mysql
  dnsNames:
  - mysql.{{ .Release.Namespace }}.svc.cluster.local
  - localhost
{{- end }}
