spring:
  application:
    name: authentication-service

server:
  port: 8180

spring:
  datasource:
    url: ${RELATIONAL_JDBC_URL:jdbc:mysql://localhost:3306/kryption}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      validation-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.echoseven.kryption: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: authentication-service
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
