eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    appname: authentication-service
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

logging:
  file: /data/logs/auth-service.log
