server:
  port: 8180

spring:
  application:
    name: authentication-service
  profiles:
    active: local
  datasource:
    url: ${RELATIONAL_JDBC_URL:jdbc:mysql://localhost:3306/demoapp}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      validation-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.github.maly7: debug

demoapp:
  jwt:
    secret: keys/private_key.der
