version: '3'

services:
  mongodb:
    image: mongo:3.6.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - main
    volumes:
      - "mongodb-data:/data/db"
  rabbit-boot:
    container_name: rabbit-boot
    build: ../rabbitmq/
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "15674:15674"
      - "5672:5672"
    expose:
      - "15672"
      - "15674"
      - "5672"
    networks:
      - main
networks:
  main:
volumes:
  mongodb-data:
