version: '3'

services:
  mongodb:
    image: mongo:3.6.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - main
    volumes:
      - "mongodb-data:/data/db"

networks:
  main:
volumes:
  mongodb-data:
