version: '3'

services:
  rabbit-test:
    container_name: rabbit-test
    build: ../rabbitmq/
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15672"
      - "5672"
    networks:
      - main
networks:
  main:
