apiVersion: v1
kind: Service
metadata:
  name: api-gateway-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: tomcat
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: api-gateway
  name: api-gateway
spec:
  replicas: $appReplicas
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - env:
        - name: eureka.client.service-url.default-zone
          value: http://service-registry.kryption.svc.cluster.local/eureka
        - name: RABBIT_HOST
          value: rabbit.kryption.svc.cluster.local
        image: ${repo}api-gateway:latest
        name: api-gateway
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-gateway
