apiVersion: v1
kind: Service
metadata:
  name: api-gateway-lb
spec:
  type: $lbtype
  ports:
    - port: 80
      targetPort: 8080
      name: tomcat
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: api-gateway
  name: api-gateway
spec:
  replicas: $appReplicas
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - env:
        - name: eureka.client.service-url.default-zone
          value: http://service-registry.default.svc.cluster.local/eureka
        - name: RABBIT_HOST
          value: rabbit.default.svc.cluster.local
        image: ${repo}api-gateway:$version
        name: api-gateway
        imagePullPolicy: $imagePullPolicy
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
          - mountPath: /certs
            name: certs
          - mountPath: /trusts
            name: trusts
      restartPolicy: Always
      volumes:
        - name: certs
          secret:
            secretName: api-gateway-tls
        - name: trusts
          secret:
            secretName: ca-key-pair
            items:
              - key: tls.crt
                path: tls.crt
  selector:
    matchLabels:
      app: api-gateway
