apiVersion: v1
kind: Service
metadata:
  labels:
    service: authentication-service
  name: authentication-service
spec:
  ports:
  - name: tomcat
    port: 8180
    targetPort: 8180
  selector:
    app: authentication-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: authentication-service
  name: authentication-service
spec:
  replicas: $appReplicas
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - env:
        - name: eureka.client.service-url.default-zone
          value: http://service-registry.default.svc.cluster.local/eureka
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: spring.datasource.username
          value: kryption
        - name: spring.datasource.url
          value: jdbc:mysql://mysql.default.svc.cluster.local:3306/kryption?autoReconnect=true&useSSL=true&verifyServerCertificate=false
        - name: eureka.instance.hostname
          value: authentication-service.default.svc.cluster.local
        image: ${repo}authentication-service:$version
        name: authentication-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8180
        volumeMounts:
          - mountPath: /certs
            name: certs
          - mountPath: /trusts
            name: trusts
      restartPolicy: Always
      volumes:
        - name: certs
          secret:
            secretName: authentication-service-tls
        - name: trusts
          secret:
            secretName: ca-key-pair
            items:
              - key: tls.crt
                path: tls.crt
  selector:
    matchLabels:
      app: authentication-service
