apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbit
  name: rabbit
spec:
  ports:
  - name: management
    port: 15672
    targetPort: 15672
  - name: rabbitmq
    port: 15674
    targetPort: 15674
  - name: sockets
    port: 5672
    targetPort: 5672
  selector:
    app: rabbit
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-admin
spec:
  type: $lbtype
  ports:
    - port: 80
      targetPort: 15672
      name: management
  selector:
    app: rabbit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: rabbit
  name: rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      initContainers:
        - name: copy-rabbitmq-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/* /etc/rabbitmq']
          volumeMounts:
            - mountPath: /configmap
              name: configmap
            - mountPath: /etc/rabbitmq
              name: config
      containers:
      - image: rabbitmq:3-management
        name: rabbit
        ports:
        - containerPort: 15672
        - containerPort: 15674
        - containerPort: 5672
        volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbit-data
          - mountPath: /etc/rabbitmq/
            name: config
          - mountPath: /certs
            name: certs
          - mountPath: /trusts
            name: trusts
      hostname: rabbit1
      restartPolicy: Always
      volumes:
        - name: rabbit-data
          persistentVolumeClaim:
            claimName: rabbit-data
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: rabbit-config
        - name: certs
          secret:
            secretName: rabbit-tls
        - name: truts
          secret:
            secretName: ca-key-pair
            items:
              - key: tls.crt
                path: tls.crt
  selector:
    matchLabels:
      app: rabbit
