apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-registry
  name: service-registry
spec:
  ports:
  - name: eureka
    protocol: TCP
    port: 443
    targetPort: 8761
  selector:
    app: service-registry
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-lb
spec:
  type: $lbtype
  ports:
  - port: 80
    targetPort: 8761
    name: eureka
  selector:
    app: service-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: service-registry
  name: service-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - env:
        - name: eureka.client.service-url.default-zone
          value: https://service-registry.default.svc.cluster.local/eureka
        name: service-registry
        image: ${repo}service-registry:$version
        imagePullPolicy: $imagePullPolicy
        ports:
        - containerPort: 8761
        volumeMounts:
        - mountPath: /certs
          name: certs
        - mountPath: /trusts
          name: trusts
      restartPolicy: Always
      volumes:
      - name: certs
        secret:
          secretName: service-registry-tls
      - name: trusts
        secret:
          secretName: ca-key-pair
          items:
          - key: tls.crt
            path: tls.crt
  selector:
    matchLabels:
      app: service-registry
