apiVersion: v1
kind: Service
metadata:
  name: {{ template "api-gateway.name" .  }}
  labels:
    service: {{ template "api-gateway.name" .  }}
    chart: {{ template "api-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "api-gateway.name" .  }}
