apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: api-gateway
  namespace: default
spec:
  secretName: api-gateway-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: api-gateway
  dnsNames:
  - api-gateway.default.svc.cluster.local
  - localhost
