apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: service-registry
  namespace: default
spec:
  secretName: service-registry-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: service-registry
  dnsNames:
  - service-registry.default.svc.cluster.local
  - localhost
