apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chat-service.name" . }}
  labels:
    deployment: {{ template "chat-service.name" . }}
    chart: {{ template "chat-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "chat-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "chat-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}{{ template "chat-service.name" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
          - name: eureka.client.service-url.default-zone
            value: https://{{ template "eureka.hostname" . }}/eureka
          - name: eureka.instance.hostname
            value: {{ template "chat-service.hostname" . }}
          - name: spring.data.mongodb.host
            value: {{ template "mongodb.hostname" . }}
          - name: spring.data.mongodb.password
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb.existingSecret }}
                key: mongodb-password
          - name: spring.data.mongodb.uri
            value: mongodb://{{ template "mongodb.hostname" . }}/{{ .Values.mongodb.mongodbDatabase }}?ssl=true
          - name: spring.data.mongodb.username
            value: {{ .Values.mongodb.mongodbUsername }}
          - name: spring.rabbitmq.host
            value: {{ template "rabbitmq.discovery.hostname" . }}
          - name: spring.rabbitmq.password
            valueFrom:
              secretKeyRef:
                name: {{ .Values.rabbitmqExistingSecret }}
                key: rabbitmq-password
          - name: spring.rabbitmq.username
            value: {{ .Values.rabbitmqUsername }}
          - name: spring.rabbitmq.port
            value: {{ .Values.amqpsNodePort | quote }}
          - name: spring.data.mongodb.authentication-database
            value: {{ .Values.mongodb.mongodbDatabase | quote }}
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "chat-service.name" . }}-secrets
                key: keyStorePassword
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "chat-service.name" . }}-secrets
                key: trustStorePassword
          - name: JAVA_OPTS
            value: {{ .Values.javaOpts | quote }}
          volumeMounts:
            - mountPath: /certs
              name: certs
            - mountPath: /trusts
              name: trusts
      restartPolicy: Always
      volumes:
        - name: certs
          secret:
            secretName: chat-service-tls
        - name: trusts
          secret:
            secretName: ca-key-pair
            items:
            - key: tls.crt
              path: tls.crt
