apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  labels:
    app: {{ template "chat-service.name" . }}
    chart: {{ template "chat-service.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mongodb-root-password: {{ uuidv4 | b64enc | quote }}
  mongodb-password: {{ uuidv4 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chat-service.name" . }}-secrets
  labels:
    chart: {{ template "chat-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  trustStorePassword: {{ .Values.trustStorePassword | default uuidv4 | b64enc}}
  keyStorePassword: {{ .Values.keyStorePassword | default uuidv4 | b64enc }}
