version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: kryption
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - main
    volumes:
      - "mysql-data:/var/lib/mysql"

networks:
  main:
volumes:
  mysql-data:
