eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: chat-service
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
