server:
  port: 8280

spring:
  application:
    name: chat-service
  profiles:
    active: local
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: kryption
      host: ${MONGODB_HOST:localhost}
      port: 27017
      uri: ${MONGODB_URL:mongodb://localhost/kryption}
  rabbitmq:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.echoseven.kryption: debug
