eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    appname: chat-service
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

logging:
  file: /data/logs/chat-service.log
