server:
  port: 8280

spring:
  application:
    name: chat-service
  profiles:
    active: local
  cloud:
    httpclientfactories:
      ok:
        enabled: true
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: demoapp
      host: ${MONGODB_HOST:localhost}
      port: 27017
      uri: ${MONGODB_URL:mongodb://localhost/demoapp}
  rabbitmq:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    host: ${RABBITMQ_HOST:localhost}
    template:
      retry:
        enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.github.maly7: debug

chat:
  messaging:
    user-exchange: user.updates

auth:
  url: http://authentication-service
