eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    appname: chat-service
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    secure-port: 443
    secure-port-enabled: true
    non-secure-port-enabled: false

logging:
  file: /data/logs/chat-service.log
