replicaCount: 1

image:
  repository:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 443
  nodePort: 30000

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
  - localhost
  issuer: ca-issuer
  tls:
  - secretName: api-gateway-ingress-tls
    hosts:
    - localhost
