replicaCount: 1

image:
  repository:
  tag: latest
  pullPolicy: IfNotPresent

keyStorePassword:
trustStorePassword:
javaOpts: -Xmx2000m -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=cloud  -Djavax.net.ssl.trustStore=/app/trusts.jks

service:
  type: NodePort
  port: 443
  nodePort: 30000

ingress:
  enabled: false
  commonName: Kryption
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
  - localhost
  issuer: ca-issuer
  tls:
  - secretName: api-gateway-ingress-tls
    hosts:
    - localhost
