image:
  tage: 0.2.0

claims:
  mongodb:
    annotations:
      volume.beta.kubernetes.io/storage-class: managed-premium

rabbitmq-ha:
  service:
    type: LoadBalancer
  persistentVolume:
    enabled: true
    size: 15Gi
    annotations:
      volume.beta.kubernetes.io/storage-class: managed-premium
