spring:
  data:
    mongodb:
      port: 27017
      username: test
      password: test
  mongodb:
    embedded:
      version: 3.2.2
  rabbitmq:
      username: guest
      password: guest
logging:
  level:
    org.springframework.web: debug

auth:
  url:
    http://localhost:8089

mongodb:
  basic-auth: false
