apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "authentication-service.name" . }}
  labels:
    deployment: {{ template "authentication-service.name" . }}
    chart: {{ template "authentication-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "authentication-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "authentication-service.name" . }}
    spec:
      containers:
        name: {{ template "authentication-service.name" . }}
        image: "{{ .Values.image.repository }}{{ template "authentication-service.name" . }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: https
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: certs
        - mountPath: /trusts
          name: trusts
      - env:
        - name: eureka.client.service-url.default-zone
          value: https://service-registry.{{ .Release.Namespace }}.svc.cluster.local/eureka
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: spring.datasource.username
          value: kryption
        - name: spring.datasource.url
          value: jdbc:mysql://mysql.{{ .Release.Namespace }}.svc.cluster.local:3306/kryption?autoReconnect=true&useSSL=true&verifyServerCertificate=false
        - name: eureka.instance.hostname
          value: https://authentication-service.{{ .Release.Namespace }}.svc.cluster.local
      restartPolicy: Always
      volumes:
      - name: certs
        secret:
          secretName: authentication-service-tls
      - name: trusts
        secret:
          secretName: ca-key-pair
          items:
          - key: tls.crt
            path: tls.crt
