apiVersion: v1
kind: Service
metadata:
  name: {{ template "authentication-service.name" . }}
  labels:
    service: {{ template "authentication-service.name" . }}
    chart: {{ template "authentication-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "authentication-service.name" . }}
