apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: api-gateway
  name: api-gateway
  namespace: kryption
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - env:
        - name: EUREKA_URL
          value: http://service-registry.kryption.svc.cluster.local:8761/eureka
        image: kryptioneastus.azurecr.io/api-gateway:latest
        name: api-gateway
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-lb
  namespace: kryption
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: tomcat
    - port: 80
      name: http
  selector:
    app: api-gateway
