apiVersion: v1
kind: Service
metadata:
  labels:
    service: authentication-service
  name: authentication-service
  namespace: kryption
spec:
  ports:
  - name: tomcat
    port: 8180
    targetPort: 8180
  selector:
    app: authentication-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: authentication-service
  name: authentication-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - env:
        - name: eureka.client.service-url.default-zone
          value: http://service-registry.kryption.svc.cluster.local/eureka
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: spring.datasource.username
          value: kryption
        - name: spring.datasource.url
          value: jdbc:mysql://mysql.kryption.svc.cluster.local:3306/kryption?autoReconnect=true&useSSL=true&verifyServerCertificate=false
        - name: eureka.instance.hostname
          value: authentication-service.kryption.svc.cluster.local
        image: kryptioneastus.azurecr.io/authentication-service:latest
        name: authentication-service
        ports:
        - containerPort: 8180
      restartPolicy: Always
  selector:
    matchLabels:
      app: authentication-service
