apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: authentication-service
  name: authentication-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - env:
        - name: EUREKA_URL
          value: http://service-registry:8761/eureka/
        - name: MYSQL_PASSWORD
        - name: MYSQL_USER
        - name: RELATIONAL_JDBC_URL
          value: jdbc:mysql://mysql:3306/kryption?autoReconnect=true
        image: kryptioneastus.azurecr.io/authentication-service:latest
        name: authentication-service
        ports:
        - containerPort: 8180
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: authentication-service
