apiVersion: v1
kind: Service
metadata:
  labels:
    service: authentication-service
  name: authentication-service
spec:
  ports:
  - name: "8180"
    port: 8180
    targetPort: 8180
  selector:
    service: authentication-service
