apiVersion: v1
kind: Service
metadata:
  labels:
    service: chat-service
  name: chat-service
spec:
  ports:
  - name: "8280"
    port: 8280
    targetPort: 8280
  selector:
    service: chat-service
