apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: chat-service
  name: chat-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - env:
        - name: EUREKA_URL
          value: http://service-registry:8761/eureka/
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_PASSWORD
        - name: MONGODB_URL
          value: mongodb://mongodb/kryption
        - name: MONGODB_USER
        - name: RABBITMQ_HOST
          value: rabbit
        - name: RABBITMQ_PASS
        - name: RABBITMQ_USER
        image: kryptioneastus.azurecr.io/chat-service:latest
        name: chat-service
        ports:
        - containerPort: 8280
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: chat-service
