apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: kryption
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: rootpassword
        - name: MYSQL_USER
          value: kryption
        image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        - mountPath: /var/log/mysql
          name: mysql-logs
      restartPolicy: Always
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: mysql-logs
        persistentVolumeClaim:
          claimName: mysql-logs
  selector:
    matchLabels:
      db: mysql
