apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: rabbit
  name: rabbit
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_VHOST
          value: /
        - name: RABBITMQ_ERLANG_COOKIE
        image: kryptioneastus.azurecr.io/rabbitmq:3-web-stomp
        name: rabbit
        ports:
        - containerPort: 15672
        - containerPort: 15674
        - containerPort: 5672
        resources: {}
      hostname: rabbit1
      restartPolicy: Always
  selector:
    matchLabels:
      app: rabbit
