apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: service-registry
  name: service-registry
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: kryptioneastus.azurecr.io/service-registry:latest
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: service-registry
