apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: service-registry
  name: service-registry
  namespace: kryption
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - env:
        - name: EUREKA_URL
          value: http://service-registry.kryption.svc.cluster.local:8761/eureka
        name: service-registry
        image: kryptioneastus.azurecr.io/service-registry:latest
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: service-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-registry
  name: service-registry
  namespace: kryption
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    app: service-registry
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-lb
  namespace: kryption
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      name: eureka
  selector:
    app: service-registry
